name: Brunoczim - GH Pages
on: 
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Get Zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.17.1

      - name: Build site
        run: zola build

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
